version: '3.8'

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: flowforge-db
    environment:
      POSTGRES_DB: flowforge
      POSTGRES_USER: flowforge
      POSTGRES_PASSWORD: flowforge_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flowforge -d flowforge"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application FlowForge
  flowforge:
    build: .
    container_name: flowforge-app
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://flowforge:flowforge_password@postgres:5432/flowforge
      # ⚠️ Remplacez ces valeurs par vos vraies clés
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/usr/src/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

